- name: Execute JavaScript inline
  # You may pin to the exact commit or the version.
  # uses: satackey/action-js-inline@bf6fcaf35de1ed03bcfd25a0a8b1fa4c551ec908
  uses: satackey/action-js-inline@v0.0.2
  with:
    # The package manager used to install the required packages.
    package-manager: yarn
    # Required package to run JavaScript snippet.
    required-packages: # optional
    # The JavaScript snippet to be executed.
    script: console.log('Hello')
